### ISSUE TITLE
Autosuggestion menu partially stays on screen while typing

### ISSUE THREAD

**Issue by maxigaz** [vonshednob/pter#8] opened 2021-11-08 09:37 UTC
In pter 2.1.0, running in Alacritty 0.9.0 on Manjaro Linux, a part of the autosuggestion menu remains visible while typing a new task entry.

See the screencast below:

https://user-images.githubusercontent.com/10419911/140717919-da3d94a5-3f6e-4f69-9580-52b93796f02c.mp4

Here's the [todo.txt](https://github.com/vonshednob/pter/files/7495780/todo.txt) file I used for testing.

**Comment by vonshednob** [comment] 2021-11-10 21:04
Thanks for pointing it out! I found the cause and will release the fix soon. Along with some documentation on how to configure the completion shortcuts.

**Comment by vonshednob** [comment] 2021-11-12 07:28
Fixed in [2.2.0](https://github.com/vonshednob/pter/blob/master/CHANGELOG.md#220).

**Closed by vonshednob** 2021-11-12 07:28 UTC
Labels: bug
