### ISSUE TITLE
Bug: chained keybindings do not seem to work on the Help screen

### ISSUE THREAD

**Issue by andrei-a-papou** [vonshednob/pter#59] opened 2024-03-04 21:09 UTC
![image](https://github.com/vonshednob/pter/assets/30468319/0e1efc7d-2993-4319-b41f-f7e9f8948ae3)

I'm using `Ctrl + x, q` for `quit` to keep myself from accidentally quitting the app (a plain `q` is too easy to hit). I've just noticed that this binding has no effect on the Help screen, even though it seems to be recognized. Single-key bindings work fine, as does `Ctrl + C`.

**Comment by vonshednob** [comment] 2024-03-05 06:48
Oh, interesting! I’ll have a look at that.

**Comment by vonshednob** [comment] 2024-03-16 07:59
Yeah, that simply was not implemented at all. While at it, I also fixed the strange scrolling behaviour (I had to press the cursor key a bunch of times before it started scrolling).

Try it out [with the latest commit](https://codeberg.org/vonshednob/pter/commit/fbdbaf493e3ffac29d4547cfcc3cd5408054d6c4)!

**Comment by andrei-a-papou** [comment] 2024-03-16 22:53
Chained keybindings on Help screen mostly work, but there are some hiccups:

1. I use `^Xq` to exit Help screen. The combination works, but after returning to the main screen, `^X` remains painted at the bottom of the screen.
2. On the Help screen, if I press `^X`, there's no way to cancel (except by hitting `q` and exiting). On the main screen, I can press `^X` and then a random key (or simply do a `^C`) to break the chain. 
3. There's no feedback for non-existing keys on the Help screen. On the main screen, pter prints a _No such keybinding_ error and cancels the chain.

**Comment by vonshednob** [comment] 2024-03-17 08:11
Hm, good one. The happy paths worked :sweat_smile: 
Try with this: [ef741a1d03](https://codeberg.org/vonshednob/pter/commit/ef741a1d03f41a16faa66399f1ad605545d3d373)

**Comment by andrei-a-papou** [comment] 2024-03-17 10:59
This is much nicer, thank you!

Strangely, though `^L` doesn't seem to refresh things and pter shows the _No such keybinding_ error.

As a side note, do we really need _Quit_ and _Refresh screen_ on the Help screen? Maybe just leave the _Cancel_ "button"? It does the same thing as _Quit_ anyway.

**Comment by vonshednob** [comment] 2024-03-17 11:18
I think the problem is that the help bar does not actually show the commands available in the help screen, but keeps showing the general pter shortcuts :thinking:

The fact that it accepts both quit and cancel is … uhm, historical? Not much thinking ever went into the help bar on the help screen; for kinda obvious reasons, I think. But yeah, it should still be correct, helpful, and consistent.

**Comment by vonshednob** [comment] 2024-03-17 13:25
You know what? `quit` should actually quit (talk about being consistent) and `cancel` should only close the help screen.

So the help bar stays as it is, but quit actally quits and refresh now works.

**Comment by andrei-a-papou** [comment] 2024-03-17 13:48
> You know what? quit should actually quit (talk about being consistent) and cancel should only close the help screen.

In terms of consistency, I agree 100%!

However, maybe I'm missing something, but why would you want to quit the app from the Help screen? Especially with the default `q` binding that's all too easy to hit -- and then it's good-bye my complex unsaved search, for example. 

1. I'm not sure making hints on Help screen configurable is worth it, so maybe just removing the "Quit" hint is easiest? 

2. Or at least moving it to the far right, so it's not the first hint/action?  In which case (also for consistency) I would make the "Quit" action come last on the main screen too.

What do you think?

**Comment by vonshednob** [comment] 2024-03-17 13:59
Maybe not just removing the quit hint, but the functionality altogether :thinking: but then I'll have to protect the user from locking themselves in (like it's done with the `quit` function).

Having quit as the first help option in the main screen is intentional: sure, the help bar could deploy some backpack-problem solution to ensure that the last help option is `quit`, but it's so much easier to show it as the first option. pter shouldn't be the vi/vim of TUI task managers ;)

**Comment by andrei-a-papou** [comment] 2024-03-17 14:43
> but then I'll have to protect the user from locking themselves in

I'm not sure I follow... You can always "Cancel"/`^C`, go back to main screen and quit from there, no?

> Having quit as the first help option in the main screen is intentional

It's your call -- after all, the main screen hints are fully configurable :)

**Comment by vonshednob** [comment] 2024-03-17 15:16
> > but then I'll have to protect the user from locking themselves in
> 
> I'm not sure I follow... You can always "Cancel"/`^C`, go back to main screen and quit from there, no?

Oh, allow me to elaborate: since a user might configure `q = nop`, pter will not start if there is no shortcut to quit.

Similarly pter should deny to start if there is no shortcut for `cancel`, because otherwise a user might get stuck in the help screen since `quit` won't be accessible in the help screen either.

> > Having quit as the first help option in the main screen is intentional
> 
> It's your call -- after all, the main screen hints are fully configurable :)

True, true. So many new features; it's admittedly hard to keep track :sweat_smile:

**Comment by andrei-a-papou** [comment] 2024-03-17 19:14
Ah, I see, but doesn't pter already check for `quit = nop` and `cancel = nop`? I just checked and it already refuses to start if either is unset.

**Comment by vonshednob** [comment] 2024-03-18 21:09
> Ah, I see, but doesn't pter already check for `quit = nop` and `cancel = nop`? I just checked and it already refuses to start if either is unset.

What? You're right, it already does… I had no idea. `git blame` says it's been a year though, so that's way beyond the event horizon.

> > True, true. So many new features
> 
> It's time to release them, then ;)

It really is. I'll still remove `quit` from the help screen functions though. And let's see if the scrolling can be fixed into submission.

**Comment by andrei-a-papou** [comment] 2024-03-20 11:15
> It really is. I'll still remove quit from the help screen functions though.

I just tried the latest commit, and the `quit` function on Help screen no longer works via keybinding. But the hint for it is still there, FYI

**Comment by vonshednob** [comment] 2024-03-20 17:39
Argh. Yeah, fixed that.

**Comment by andrei-a-papou** [comment] 2024-03-20 17:43
Works, thank you!

**Comment by vonshednob** [comment] 2024-03-20 17:56
I'll plan to release 3.16 then later this week, hoping that nothing else gets in the way. I'm halfway considering giving this release the nickname 'andrei-a-papou'.

**Comment by andrei-a-papou** [comment] 2024-03-20 18:12
Thank you, but no need: you've already mentioned me in git commits, this is plenty :)

**Comment by vonshednob** [comment] 2024-03-23 09:41
Closing this, so I don't have to feel bad to release with pending issues in the milestone.

**Closed by vonshednob** 2024-03-23 09:41 UTC

**Comment by andrei-a-papou** [comment] 2024-03-23 10:46
Tested again, things seem to be working fine here!
